### ISSUE TITLE
Conversion Not Working

### ISSUE THREAD

**Issue by ob7** [Monnoroch/ColorHighlighter#248]
When I do ctrl shift a for color convert, and type rgba to make a hex go rgba, it does nothing.  The console will output something like this:

ChReplaceColor: {'words': "((243, 247), 'rgba', '#FFFF00FF')"}

but no change to document.

Any ideas what could be causing that?

**Comment by jCrip** [comment]
Still not working. same issue here

The console will output:
ChReplaceColor: {'words': "((37, 44), 'hsl()', '#1ed760FF')"}

and nothing happens.

OSX Yosemite, ST3 3095

**Comment by Monnoroch** [comment]
Please, provide the text sample.

**Comment by jCrip** [comment]
When trying to on this, or something like this:
```css
.btn-video {
	/*opacity: 0.4;*/
	position: relative;
	border: 2px solid #1ed760;
	/*background-color: rgba(0, 0, 0, 0.4);*/
	background-color: hsla(0, 0%, 0%, 0.4);
	top: 50%;
}
```

nothing happen

And with the last update the console now show:
```
Traceback (most recent call last):
  File "ColorHighlighter in /Users/xxxxx/Library/Application Support/Sublime Text 3/Installed Packages/Color Highlighter.sublime-package", line 1745, in do_run
NameError: global name 'fmt' is not defined
```

Instead of: `ChReplaceColor: {'words': "((37, 44), 'hsl()', '#1ed760FF')"}` like before
