### ISSUE TITLE
Add support for CSS variables

### ISSUE THREAD

**Issue by thematho** [Monnoroch/ColorHighlighter#269]
It would be great if CSS variables support is added i don't known if this is possible. E.G.
```css
:root {
  --my-color: #a6c776; // This color code is highlighted properly
}
.element {
  background: var(--my-color); // --my-color variable should be highlighted using the color #a6c776
}
```

The [**W3 specification**](http://www.w3.org/TR/css-variables/) is not stable yet, however the draft hasn't change since 6 May 2014 and We can start using this feature with polyfills like [**Myth.io**](http://www.myth.io/)
