### ISSUE TITLE
convert error

### ISSUE THREAD

**Issue by yuchisu** [Monnoroch/ColorHighlighter#299]
console error message
```
convert error:
'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte
```
and CH dosen't work with many color codes
![qq 20160307172459](https://cloud.githubusercontent.com/assets/15692084/13565205/a6fd8788-e489-11e5-9eed-b610af53038c.jpg)

**Comment by Js-GitHub** [comment]
### Two Colors below work, see screen capture lines #24, 25

color: #68CDD0;  /* these colors work */
color: #22292C;  /* these colors work */



![colorhighlighter-demo-css-2-colors-ok](https://cloud.githubusercontent.com/assets/10727620/13569924/e58c341e-e41f-11e5-8dfe-ffd80d344a08.PNG)

**Comment by Monnoroch** [comment]
@yuchisu Please, try the code from this commit: https://github.com/Monnoroch/ColorHighlighter/commit/ba05905d37f7f63b3baf556bb2681d11fab901ef.

**Comment by yuchisu** [comment]
@Js-GitHub  I'm sorry I didn't give enough information cause this is my first time to ask a question on github.  I'm using the ST3 Build 3103 on win10. And I've tried reinstalling CH.  I find it works normally when I'm taking the screenshot, but it get lose again after I restart the ST. 

![qq 20160307214315](https://cloud.githubusercontent.com/assets/15692084/13571318/22e7d5fe-e4af-11e5-9a7e-eb2f3a134d56.jpg)
![qq 20160307172459](https://cloud.githubusercontent.com/assets/15692084/13571317/22ded148-e4af-11e5-8a12-53222f2f6018.jpg)

**Comment by Js-GitHub** [comment]
@yuchisu
No problem, I'm new myself.

##### Save copy of:   Preferences > Package Settings > Color Highlighter > Settings - User

##### Remove everything from file above except following:
###### Set "ha_style": "filled"

![colorhighlighter-preferences-package-setting-default](https://cloud.githubusercontent.com/assets/10727620/13572059/182d9658-e42d-11e5-9b0d-0b04824d8e80.PNG)

##### Lets start out with basics to troubleshoot and once we get it working you can customize
###### "enable": true...  not needed as it's already true in Settings - Default
###### Not sure what "ha_icons & style" does so lets use what's in Settings - Default for now

##### Create a file named: "color_highlighter_demo.css" with following code so we're comparing apples to apples:

```css
/*ColorHighlighter Demo */

.class {
    color: black;
    color: #000;
    color: white;
    color: #FFF;
    color: grey;
    color: red;
    color: #F00;
    color: green;
    color: #0F0;
    color: blue;
    color: #00F;
    color: gold;
    color: pink;
    color: fuchsia;
    color: lime;
    color: purple;
    color: brown;
    color: orange;
    color: lightblue;
    color: yellow;
    color: #68CDD0;  /* these colors work */
    color: #22292C;   /* these colors work */
}
```

### Save all changes above.  Restart Sublime Text ( exit / close it, then reopen it ).
####  Open "color_highlighter_demo.css" file
